### ISSUE TITLE
OMSI2 Support

### ISSUE THREAD

**Issue by 487376** [gcWorld/ibis-droid#45]
Hi,
Will be there support for OMSI2? I'm using OMSI 2.1.012 and IBIS Droid 1.3.4 and plugin in OMSI won't start. Can anyone tell me, where is a problem? I think it's in plugin, but I'm not sure.

**Comment by gcWorld** [comment]
The new App for OMSI 2 is available, [IBIScontrol](http://www.gcmods.de/downloads/ibiscontrol)
